### ISSUE TITLE
about V

### ISSUE THREAD

**Issue by old-fan-kk** [alivaramesh/MixtureDenseRegression#2]
Hi, How is the value of V obtained? Does the value of V greatly affect the result?
https://github.com/alivaramesh/MixtureDenseRegression/blob/b4edb0a2b2b4df952c1b29271a45aae731af7a8a/src/lib/trains/multi_pose.py#L77

**Comment by alivaramesh** [comment]
Hi, it is based on how different human annotations are on redundantly annotated COCO Val as explained in the dataset at [here](https://cocodataset.org/#keypoints-eval).
