### ISSUE TITLE
The mixture density network converges into a models

### ISSUE THREAD

**Issue by old-fan-kk** [alivaramesh/MixtureDenseRegression#3]
Hi, When I use my own data to train a mixture density network, the probability of one model is very large and the probability of the remaining models is very small. Have you encountered this kind of problem? Can you give me some suggestions? Thank you in advance.

**Comment by alivaramesh** [comment]
@old-fan-kk can you tell me a bit about the data you are training on? for example, what is its size and what kind of objects it contain?
